<?php
/*
 * Sylphen Data Bridge for OpenDXP
 * Copyright (c) Sylphen GmbH — https://sylphen.com
 * Based on Blackbit Data Director — Copyright (c) Blackbit digital Commerce GmbH
 * SPDX-License-Identifier: GPL-3.0-or-later
 */


namespace Sylphen\DataBridgeBundle\lib\Pim\Item\FieldMapper;

use Sylphen\DataBridgeBundle\lib\Pim\Helper;
use Sylphen\DataBridgeBundle\lib\Pim\Item\Importer;
use Sylphen\DataBridgeBundle\lib\Pim\Item\ResettableIterator;
use Sylphen\DataBridgeBundle\model\PimcoreDbRepository;
use Exception;
use OpenDxp\Model\AbstractModel;
use OpenDxp\Model\Asset;
use OpenDxp\Model\DataObject;
use OpenDxp\Model\DataObject\AbstractObject;
use OpenDxp\Model\DataObject\ClassDefinition;
use OpenDxp\Model\DataObject\ClassDefinition\Data;
use OpenDxp\Model\DataObject\Concrete;
use OpenDxp\Model\DataObject\Service;
use OpenDxp\Model\Document\PageSnippet;
use OpenDxp\Model\Element\ElementInterface;

class ElementPathMapper extends AbstractFieldMapper
{
    public function supports(array $mapping, Data $fieldDefinition, AbstractModel $dataObject = null)
    {
        return strtolower($mapping['fieldName']) === 'path';
    }

    public function map($mapping, $value, $currentValue, Data $fieldDefinition, AbstractModel $target = null)
    {
        if ($target === null && is_string($value) && @preg_match($value, '') !== false) {
            return $value;
        }

        $parentObject = $this->getParentObjectOrCreate($value);

        // not necessary in querying phase
        if ($target !== null) {
            if ($target === $parentObject) {
                $this->log($target, 'Cannot set parent object to itself', 'alert');
                return (is_callable($currentValue) ? $currentValue() : $currentValue);
            }

            if ($target instanceof ElementInterface) {
                $oldParentId = $target->getParentId();
                if ($oldParentId != $parentObject->getId()) {
                    $autoGenerated = PimcoreDbRepository::getInstance()->findOneInSql('SELECT data FROM properties WHERE ctype=? AND cid=? AND name=?', [\OpenDxp\Model\Element\Service::getElementType($target), $oldParentId, 'auto_generated']);
                    if ($autoGenerated && !PimcoreDbRepository::getInstance()->findOneInSql(
                            'SELECT 1 FROM '.\OpenDxp\Model\Element\Service::getElementType($target).'s WHERE '.($target instanceof Concrete ? Helper::prefixObjectSystemColumn('parentId') : 'parentId').'=? AND '.($target instanceof Concrete ? Helper::prefixObjectSystemColumn('id') : 'id').'!=?',
                            [$oldParentId, $target->getId()]
                        )) {
                        $target->getParent()->delete();
                    }
                }
            }

            if ($parentObject === null) {
                return (is_callable($currentValue) ? $currentValue() : $currentValue);
            }

            if ($target instanceof ElementInterface) {
                $target->setParent($parentObject);
            }
        }

        if ($target !== null) {
            $value = rtrim($parentObject->getRealFullPath(), '/').'/';
        }

        return $value;
    }

    private function getParentObjectOrCreate($value)
    {
        if (is_string($value)) {
            if(\preg_match('/^[A-Za-z0-9\\\.]+:[^:]+(::?[^:]+)*$/', $value)) {
                $itemMold = $this->itemMoldBuilder->getItemMold($this->importer->getDataport()['id']);
                $parentObject = $this->importer->getOneObjectByIdentifier($value, $itemMold);

                if (!$parentObject instanceof ElementInterface) {
                    try {
                        $objectIdentifierParts = $this->importer->getObjectIdentifierParts($value);
                        if ($objectIdentifierParts === false) {
                            $this->importer->getLogger()->warning('Could not parse data query selector "'.$value.'"');
                            return null;
                        }
                    } catch (Exception $e) {
                        $this->importer->getLogger()->warning('Could not parse data query selector "'.$value.'"');
                        return null;
                    }

                    $parentObject = $this->importer->createObject($this->itemMoldBuilder->getItemMoldByClassname($objectIdentifierParts[0]), $objectIdentifierParts[2]);
                    $referencedObjectClassDefinition = Helper::getClassDefinitionById($objectIdentifierParts[0]::classId());
                    $parentValue = $this->importer->map(['fieldName' => $objectIdentifierParts[1], 'brickName' => $objectIdentifierParts[0]], $objectIdentifierParts[2], null, Importer::getFieldDefinition($referencedObjectClassDefinition, $objectIdentifierParts[1]), $parentObject);

                    $fieldParts = explode('#', $objectIdentifierParts[1]);

                    $parentSetter = 'set'.ucfirst($fieldParts[0]);
                    $parentObject->$parentSetter($parentValue, $fieldParts[1] ?? null);
                    $parentObject->setProperty('auto_generated', 'bool', true);

                    $this->importer->saveObject($parentObject, true);

                    $this->importer->addToRelationCache($value, ['type' => \OpenDxp\Model\Element\Service::getElementType($parentObject), 'id' => $parentObject->getId()]);
                } elseif($parentObject->getId() == 0) {
                    $this->importer->saveObject($parentObject, true);
                    $this->importer->addToRelationCache($value, ['type' => \OpenDxp\Model\Element\Service::getElementType($parentObject), 'id' => $parentObject->getId()]);
                }
            } else {
                if (substr($value, 0, 1) !== '/') {
                    // relative path
                    $value = rtrim($this->importer->getItemFolder()->getRealFullPath(), '/').'/'.$value;
                }

                $objectPathArray = explode('/', $value);
                $elementType = $this->importer->getItemType();
                $objectPathArray = array_map(static function ($pathPart) use ($elementType) {
                    return Service::getValidKey($pathPart, $elementType);
                }, $objectPathArray);
                $value = implode('/', $objectPathArray);

                $itemMold = $this->itemMoldBuilder->getItemMold($this->importer->getDataport()['id']);
                $parentObject = \OpenDxp\Model\Element\Service::getElementByPath(\OpenDxp\Model\Element\Service::getElementType($itemMold), $value);

                if (!$parentObject instanceof ElementInterface) {
                    $itemCacheIterator = new ResettableIterator($this->importer->getCachedItems());
                    foreach ($itemCacheIterator as $item) {
                        if ($item->getRealFullPath() === rtrim($value, '/')) {
                            $parentObject = $item;
                            $this->importer->saveObject($parentObject, true);

                            break;
                        }
                    }
                    $itemCacheIterator->reset();
                }

                if (!$parentObject instanceof ElementInterface) {
                    $folderPath = $value;
                    if ($this->importer->getTargetConfig()['optimizeInheritance']) {
                        $parentObject = $this->createParentPath($folderPath, $itemMold);
                    } elseif ($itemMold instanceof Concrete) {
                        $parentObject = Service::createFolderByPath($folderPath);
                    } elseif ($itemMold instanceof Asset) {
                        $parentObject = Asset\Service::createFolderByPath($folderPath);
                    } elseif ($itemMold instanceof PageSnippet) {
                        if ($itemMold instanceof \OpenDxp\Model\Document\Printpage) {
                            $parentParentObject = \OpenDxp\Model\Document\Service::createFolderByPath(dirname($folderPath));
                            $parentObject = $this->importer->createObject(new \OpenDxp\Model\Document\Printcontainer(), basename($folderPath));
                            $parentObject->setParent($parentParentObject);
                            $parentObject->setController('App\Controller\Web2printController::containerAction');
                            $parentObject->setProperty('auto_generated', 'bool', true);
                            $parentObject->setPublished(true);
                            $this->importer->saveObject($parentObject, true);
                        } else {
                            $parentObject = \OpenDxp\Model\Document\Service::createFolderByPath($folderPath);
                        }
                    }
                }
            }
        } elseif (empty($value)) {
            $parentObject = $this->importer->getItemFolder();
        } elseif ($value instanceof AbstractModel) {
            $parentObject = $value;
        } elseif (is_array($value) && isset($value['fullpath'])) {
            $parentObject = Service::getElementByPath($value['type'], $value['fullpath']);
        } elseif (is_array($value) && isset($value['query'])) {
            $parentObject = $this->importer->getOneObjectByIdentifier($value['query']);
        } elseif (is_array($value) && isset($value['path'], $value['key'])) {
            $parentObject = Service::getElementByPath($value['type'], $value['path'].$value['key']);
        } elseif (is_array($value) && isset($value['path'])) {
            $parentObject = Service::getElementByPath($value['type'], $value['path']);
        } elseif (is_array($value) && isset($value[0])) {
            $this->importer->getLogger()->notice('Found multiple possible parent elements, using first one');
            $parentObject = $this->getParentObjectOrCreate($value[0]);
        }

        return $parentObject;
    }

    private function createParentPath($path, $itemBlueprint)
    {
        $current = null;
        $pathsArray = [];
        $parts = explode('/', $path);
        $parts = array_filter($parts);

        $elementType = $this->importer->getItemType();
        foreach ($parts as $part) {
            $pathPart = $pathsArray[count($pathsArray) - 1] ?? '';
            $pathsArray[] = $pathPart.'/'.Service::getValidKey($part, $elementType);
        }

        foreach ($pathsArray as $i => $currentPath) {
            $current = DataObject::getByPath($currentPath);
            if ($current === null) {
                $parentPath = ($i === 0) ? '/' : $pathsArray[$i - 1];

                $key = substr($currentPath, strrpos($currentPath, '/') + 1, strlen($currentPath));
                $object = $this->importer->createObject($itemBlueprint, $key);

                $parent = DataObject::getByPath($parentPath);
                if ($parent) {
                    $object->setParent($parent);
                    $object->setPath(rtrim($parent->getRealFullPath(), '/').'/');
                } else {
                    $object->setParentId(1);
                    $object->setPath('/');
                }

                $object->setPublished(true);
                $user = Helper::getUser();
                $object->setUserModification($user->getId());

                $object->save(['versionNote' => 'Dataport: '.$this->importer->getDataport()['id']]); // save here because Concrete::setParent() requires object to have an ID
                $current = $object;
            }
        }

        return $current;
    }
}